### ISSUE TITLE
I got an error after add numtel:publicsources package

### ISSUE THREAD

**Issue by opond** [numtel/meteor-publicsources#3] opened 2015-04-07 06:38 UTC
TypeError: Cannot call method 'toString' of null
 in .meteor/packages/meteor-tool/.1.0.41.tpc8vq++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/compiler.js:260:44

With Meteor 1.0.3.2

**Comment by numtel** [comment] 2015-04-07 20:43
Can you please post a link to a repository with the minimum amount of code to reproduce this issue?

**Comment by johanholmerin** [comment] 2015-04-11 18:19
The issue occurs when you add numtel:publicsources and mquandalle:bower. You both register source handler for json-files with a null handler. Reproduction: [johanholmerin/numtel-publicsources-issue-3](https://github.com/johanholmerin/numtel-publicsources-issue-3)

The error occurs because Meteor tries to run toString on the handler, which is null, and therefore fails. I have made a temporary fix in [johanholmerin/numtel-publicsources](https://github.com/johanholmerin/meteor-publicsources) but this behavior will most likely be broken with the next release of Meteor, see meteor/meteor#3985. Consider switching to the same solution as [Nemo64/meteor-bootstrap](https://github.com/Nemo64/meteor-bootstrap).

**Comment by numtel** [comment] 2015-04-11 23:31
This has been fixed with version 1.0.1. Following the example from [Nemo64/meteor-bootstrap](https://github.com/Nemo64/meteor-bootstrap), instead of using a file named `publicsources.json`, the file must have an extension of `.publicsources.json`. (e.g. `myapp.publicsources.json` would be valid)

Thanks @johanholmerin for investigating this issue!

I have also updated `numtel:privatesources` to include this change although apparently I had overlooked that it already functioned in this way due to the error-causing line had been commented out. Only a change to the readme was necessary.

**Closed as completed by numtel** 2015-04-11 23:31 UTC
